# Generated by Django 3.2.12 on 2024-01-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level_by_city', models.ImageField(upload_to='static/images', verbose_name='График уровень зарплат по городам')),
                ('graph_vacancy_fraction_by_city', models.ImageField(upload_to='static/images', verbose_name='График доля вакансий по городам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('photo', models.ImageField(upload_to='static/images', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level', models.ImageField(upload_to='static/images', verbose_name='График уровень зарплат по годам')),
                ('graph_num_vacancy', models.ImageField(upload_to='static/images', verbose_name='График количество вакансий по годам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField(max_length=30, verbose_name='Название таблицы')),
                ('table', models.TextField(verbose_name='Таблица')),
                ('graph_skills', models.ImageField(upload_to='static/images', verbose_name='График по скиллам')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
    ]
